// myApp/src/components/PRDView.tsx
import React from 'react';
import { FileText, Target, Users, ListChecks, Flag } from 'lucide-react';

export default function PRDView({ data }: { data: any }) {
  const { analysis_details, metadata } = data;

  return (
    <div className="p-8 max-w-4xl mx-auto space-y-12 pb-20 selection:bg-[#4729e0]/30">
      {/* 1. Document Header */}
      <div className="border-b border-slate-800 pb-8 text-center">
        <h1 className="text-4xl font-black text-white mb-2 uppercase tracking-tighter">
          Product Requirements Document (PRD)
        </h1>
        <p className="text-[#4729e0] font-bold tracking-widest text-sm italic">
          v1.0 • Generated by ReqMind AI for {metadata?.project_id}
        </p>
      </div>

      {/* 2. Executive Summary */}
      <section className="space-y-4">
        <div className="flex items-center gap-3 text-white border-l-4 border-[#4729e0] pl-4">
          <Target className="w-6 h-6 text-[#4729e0]" />
          <h2 className="text-2xl font-bold uppercase tracking-tight">1. Project Objective</h2>
        </div>
        <p className="text-slate-300 leading-relaxed pl-10">
          The goal of this initiative is to develop a {data.predicted_category || "software solution"} 
          that addresses the core needs identified in the {metadata?.source} analysis. 
          The project focuses on high-availability and user-centric workflows.
        </p>
      </section>

      {/* 3. User Stories (AI Transformation) */}
      <section className="space-y-4">
        <div className="flex items-center gap-3 text-white border-l-4 border-[#4729e0] pl-4">
          <Users className="w-6 h-6 text-[#4729e0]" />
          <h2 className="text-2xl font-bold uppercase tracking-tight">2. User Stories</h2>
        </div>
        <div className="pl-10 space-y-3">
          {analysis_details.functional_requirements?.slice(0, 5).map((req: string, i: number) => (
            <div key={i} className="p-4 bg-[#1c1a2e] border border-slate-800 rounded-xl italic text-slate-400">
              "As a <span className="text-white font-semibold">{analysis_details.stakeholders?.[0] || 'User'}</span>, 
              I want to <span className="text-white font-semibold">{req.toLowerCase()}</span>, 
              so that the system achieves its core functionality."
            </div>
          ))}
        </div>
      </section>

      {/* 4. Acceptance Criteria */}
      <section className="space-y-4">
        <div className="flex items-center gap-3 text-white border-l-4 border-[#4729e0] pl-4">
          <ListChecks className="w-6 h-6 text-[#4729e0]" />
          <h2 className="text-2xl font-bold uppercase tracking-tight">3. Acceptance Criteria</h2>
        </div>
        <ul className="pl-10 space-y-2 list-disc text-slate-400">
          {analysis_details.non_functional_requirements?.map((req: string, i: number) => (
            <li key={i}><span className="text-slate-200">{req}</span></li>
          ))}
        </ul>
      </section>
      
      {/* 5. Roadmap & Timeline */}
      <section className="space-y-4">
        <div className="flex items-center gap-3 text-white border-l-4 border-[#4729e0] pl-4">
          <Flag className="w-6 h-6 text-[#4729e0]" />
          <h2 className="text-2xl font-bold uppercase tracking-tight">4. Timeline & Release</h2>
        </div>
        <p className="pl-10 text-slate-400 italic">
          Estimated project milestones: {analysis_details.timelines?.join(" → ") || "TBD"}
        </p>
      </section>
    </div>
  );
}